import gym
import retro
from utils import resize, rgb2gray
import numpy as np
from interventions import InterventionEnv

class GymWrapper:
    def __init__(self, config):
        self.total_students = 30
        self.sel_students = 5
        self.mu = 10
        self.env = InterventionEnv(
            total_students=self.total_students,
            sel_students=self.sel_students,
            mu=self.mu,
        )  # gym.make(config.env_name)
        # self.actual_mental_states= [10, 8,9]
        # self.actual_influence = [[0 , 0.1, 0.5],
        #            [0.6, 0 , 0.4],
        #            [0.8, 0.3, 0]]

        self.actual_mental_states = [
            7,
            4,
            8,
            1,
            6,
            5,
            7,
            8,
            2,
            3,
            7,
            1,
            7,
            4,
            7,
            1,
            1,
            9,
            8,
            4,
            9,
            7,
            4,
            6,
            9,
            9,
            4,
            8,
            2,
            4,
        ]
        self.actual_influence = [
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.5,
                0.0,
                0.0,
                0.0,
                0.4,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.7,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.4,
                0.0,
                0.7,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                1.0,
                0.8,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.5,
                0.9,
                0.0,
                0.4,
                0.0,
                0.0,
                0.6,
                0.9,
                0.0,
                0.1,
                0.0,
                0.5,
                0.9,
                0.0,
                0.0,
                0.3,
                0.7,
                0.8,
                0.0,
                0.0,
                0.0,
                0.8,
                0.5,
                0.4,
                0.0,
                0.4,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.6,
                0.8,
                0.0,
                0.0,
                0.0,
                0.0,
                0.3,
                0.8,
                0.5,
                0.0,
                0.9,
                0.0,
                0.9,
                0.0,
                0.2,
                0.0,
                0.7,
                0.5,
                0.2,
                0.0,
                0.9,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.8,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.9,
                0.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                0.0,
                0.5,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.0,
                0.9,
            ],
            [
                0.0,
                0.2,
                0.0,
                0.6,
                0.0,
                0.8,
                0.0,
                0.0,
                0.0,
                0.0,
                0.3,
                0.0,
                0.2,
                0.6,
                0.0,
                1.0,
                0.0,
                0.5,
                0.0,
                0.0,
                0.8,
                0.0,
                0.0,
                0.1,
                1.0,
                0.0,
                0.1,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.4,
                0.7,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.8,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.9,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.7,
                0.0,
                0.0,
                0.0,
                0.0,
                0.7,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.8,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.8,
                0.0,
                0.2,
                0.0,
                0.5,
                0.6,
                0.7,
                0.0,
                0.6,
                1.0,
                0.8,
                0.0,
                1.0,
                0.3,
                0.0,
                0.0,
                0.0,
                0.0,
                0.8,
                1.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.5,
                0.1,
                0.5,
                0.0,
                1.0,
                0.6,
                0.9,
                0.0,
                0.0,
                0.7,
                0.2,
                0.1,
                0.0,
                1.0,
                0.1,
                0.2,
                0.6,
                0.4,
                0.0,
                0.4,
                0.0,
                0.0,
                0.6,
                0.0,
                0.7,
                0.5,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                0.0,
                0.0,
                0.7,
                0.0,
                0.9,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.9,
                0.9,
                0.1,
                0.0,
                0.0,
                0.8,
                0.5,
                0.8,
                0.8,
                0.4,
                0.0,
                0.6,
                0.6,
                0.6,
                0.4,
                0.4,
                0.8,
                1.0,
                0.2,
                0.0,
                0.7,
                0.4,
                0.9,
                0.0,
                0.0,
                0.0,
                0.4,
                0.5,
            ],
            [
                0.0,
                0.4,
                0.0,
                0.3,
                0.0,
                0.0,
                0.0,
                0.4,
                0.0,
                0.0,
                1.0,
                0.0,
                0.7,
                0.0,
                0.9,
                0.0,
                0.4,
                1.0,
                0.8,
                0.4,
                0.0,
                0.0,
                0.8,
                0.2,
                0.8,
                0.9,
                0.6,
                0.0,
                1.0,
                0.3,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.0,
                0.0,
                0.0,
                0.0,
                0.5,
                0.1,
                0.0,
                0.1,
                0.5,
                0.0,
                0.7,
                0.7,
                0.2,
                0.5,
                0.1,
                0.2,
                0.0,
                0.4,
                0.4,
                1.0,
                0.6,
                0.0,
                0.0,
                0.7,
                0.4,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.6,
                1.0,
                0.0,
                0.3,
                0.0,
                0.5,
                0.5,
                0.0,
                0.5,
                0.0,
                0.2,
                0.9,
                0.7,
                0.0,
                0.2,
                0.0,
                0.4,
                1.0,
                0.2,
                0.0,
                0.0,
                0.2,
                0.0,
                0.1,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.9,
                0.4,
                0.0,
                0.0,
                0.0,
                0.8,
                0.1,
                0.8,
                0.0,
                0.4,
                0.1,
                0.8,
                0.1,
                0.0,
                0.2,
                0.6,
                0.1,
                0.1,
                0.0,
                0.9,
                0.5,
                0.4,
                0.9,
                0.0,
                0.9,
                0.5,
                0.5,
            ],
            [
                0.0,
                0.8,
                0.0,
                0.4,
                0.0,
                0.1,
                0.8,
                0.9,
                0.0,
                0.0,
                0.8,
                0.8,
                0.3,
                0.4,
                0.8,
                0.6,
                0.6,
                0.0,
                1.0,
                0.2,
                0.9,
                0.0,
                0.8,
                0.5,
                0.9,
                1.0,
                0.2,
                0.2,
                0.0,
                0.7,
            ],
            [
                0.0,
                0.0,
                0.9,
                0.3,
                0.5,
                0.0,
                0.0,
                0.0,
                0.0,
                0.3,
                0.3,
                0.0,
                0.4,
                1.0,
                1.0,
                1.0,
                0.9,
                0.3,
                0.0,
                0.3,
                0.6,
                0.0,
                0.7,
                0.9,
                0.0,
                0.8,
                0.7,
                0.4,
                0.0,
                0.6,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.0,
                0.0,
                0.0,
                0.0,
                0.9,
                0.7,
                0.0,
                0.2,
                0.1,
                0.4,
                0.0,
                0.5,
                0.2,
                0.3,
                0.0,
                0.9,
                0.0,
                0.3,
                0.0,
                0.0,
                0.8,
                0.0,
                0.0,
                0.3,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.9,
                0.4,
                0.0,
                0.3,
                0.0,
                0.4,
                0.8,
                0.0,
                0.3,
                0.0,
                0.5,
                0.8,
                0.4,
                0.3,
                1.0,
                0.2,
                0.0,
                0.0,
                1.0,
                0.8,
                0.0,
                0.0,
                0.6,
                0.0,
                0.3,
                0.8,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.5,
                0.7,
                0.0,
                0.0,
                0.0,
                1.0,
                0.1,
                0.1,
                0.0,
                0.8,
                0.1,
                0.2,
                0.3,
                0.2,
                0.9,
                0.1,
                1.0,
                0.5,
                0.0,
                0.0,
                0.6,
                0.0,
                0.9,
                0.0,
                0.6,
                1.0,
                0.9,
            ],
            [
                0.0,
                0.7,
                0.0,
                0.8,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.3,
                0.0,
                0.1,
                0.4,
                0.5,
                0.9,
                0.5,
                0.5,
                1.0,
                0.5,
                0.0,
                0.2,
                0.7,
                0.2,
                0.0,
                0.8,
                0.3,
                0.1,
                0.0,
                0.0,
                0.4,
            ],
            [
                0.2,
                0.5,
                0.0,
                0.8,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.1,
                0.8,
                1.0,
                0.3,
                0.3,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.2,
                0.6,
                0.0,
                0.6,
                0.3,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.1,
                0.0,
                0.0,
                0.9,
                0.4,
                0.0,
                0.1,
                0.8,
                0.6,
                0.3,
                0.0,
                0.5,
                0.9,
                0.4,
                1.0,
                0.0,
                0.0,
                1.0,
                0.4,
                0.2,
            ],
            [
                0.0,
                1.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.5,
                0.2,
                0.0,
                0.5,
                0.0,
                0.0,
                0.1,
                0.6,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.3,
                0.0,
                0.2,
                0.0,
                0.1,
                0.0,
                0.0,
                0.0,
                0.0,
                0.9,
                0.8,
                0.4,
                1.0,
                0.0,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.6,
                0.0,
                0.0,
                0.9,
                1.0,
            ],
            [
                0.8,
                0.0,
                0.0,
                0.0,
                0.2,
                0.0,
                0.0,
                0.0,
                0.0,
                0.4,
                0.4,
                0.0,
                0.5,
                0.4,
                0.2,
                0.0,
                0.5,
                0.0,
                0.0,
                0.6,
                0.4,
                0.0,
                0.2,
                0.0,
                1.0,
                0.9,
                0.0,
                0.9,
                0.0,
                0.5,
            ],
            [
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                0.0,
                1.0,
                0.0,
                0.0,
                0.5,
                0.0,
                0.0,
                1.0,
                0.7,
                0.3,
                1.0,
                0.1,
                0.4,
                0.5,
                0.0,
                0.2,
                0.0,
                0.6,
                0.7,
                0.7,
                0.4,
                0.0,
                0.2,
                0.1,
                0.0,
            ],
        ]
        self.env.set_actual_states(self.actual_mental_states, self.actual_influence)
        self.screen_width, self.screen_height = (
            config.screen_width,
            config.screen_height,
        )
        self.reward = 0
        self.terminal = True
        self.info = {"ale.rounds": 0}
        self.random_start = config.random_start
        self.action_space = self.env.action_space
        self._state = None
        # self._screen = np.empty((210, 160), dtype=np.uint8)
        self.rounds = 5

    def new_game(self):
        if self.rounds == 5:
            self._state = self.env.reset()
        self._step(0)
        self.reward = 0
        self.action = 0

    def new_random_game(self):
        self.new_game()
        for _ in range(np.random.randint(0, self.random_start)):
            self._step(0)

        self.rounds = self.rounds - 1
        if self.rounds == -1:
            self.rounds = 5

    def _step(self, action):
        self.action = action
        self.state, self.reward, self.terminal, self.info = self.env.step(action)

    def random_step(self):
        return self.action_space.sample()

    def act(self, action):
        rounds_before = self.rounds
        self._step(action)
        if self.rounds < rounds_before:
            self.terminal = True

    def act_play(self, action):
        rounds_before = self.rounds
        self._step(action)
        # self.env.render()
        if self.rounds < rounds_before:
            self.terminal = True

    def new_play_game(self):
        self.new_game()
        self._step(1)

    @property
    def screen(self):
        a = resize(
            self.make_image(self._state), (self.screen_height, self.screen_width)
        )
        return a

    def rgb2gray(self, rgb):
        return np.dot(rgb[..., :3], [0.2989, 0.5870, 0.1140])

    def make_image(self, this_state):
        w, h = 512, 512
        data = np.zeros((h, w, 3), dtype=np.uint8)
        state = this_state.reshape((self.total_students + 1) * self.total_students)
        grid_size = int(w / len(state))
        for i in range(len(state)):
            for j in range(i * grid_size, ((i + 1) * grid_size)):
                for k in range(512):
                    data[j, k] = [state[i] * 25, state[i] * 25, state[i] * 25]
        # img = Image.fromarray(data, 'RGB')
        gray = self.rgb2gray(data)
        return gray
        # img.save('my.png')
        # img.show()

    # @property
    # def rounds(self):
    #     return 5


class RetroWrapper:
    def __init__(self, config):
        """
        TODO !!! Reward Shaping!!!
        Parameters
        ----------
        config
        """
        self.env = retro.make(
            game=config.env_name, state=config.state, use_restricted_actions=2
        )
        self.screen_width, self.screen_height = (
            config.screen_width,
            config.screen_height,
        )
        self.reward = 0
        self.terminal = True
        self.info = {"rounds": 0}
        self.frameskip = config.frame_skip
        self.random_start = config.random_start
        buttons = [
            "B",
            "A",
            "MODE",
            "START",
            "UP",
            "DOWN",
            "LEFT",
            "RIGHT",
            "C",
            "Y",
            "X",
            "Z",
        ]
        actions = [
            ["LEFT"],
            ["RIGHT"],
            ["LEFT", "DOWN"],
            ["RIGHT", "DOWN"],
            ["DOWN"],
            ["DOWN", "B"],
            ["B"],
        ]
        self._actions = []
        for action in actions:
            arr = np.array([False] * 12)
            for button in action:
                arr[buttons.index(button)] = True
            self._actions.append(arr)
        self.action_space = gym.spaces.Discrete(len(self._actions))
        print(self.action_space.sample())

    def new_game(self):
        if self.rounds == 0:
            self.env.reset()
        self._step(0)
        self.reward = 0
        self.action = 0

    def new_random_game(self):
        self.new_game()
        for _ in range(np.random.randint(0, self.random_start)):
            self._step(0)

    def new_play_game(self):
        self.new_game()
        self._step(1)

    def _step(self, action):
        self.action = action
        self._screen, self.reward, self.terminal, self.info = self.env.step(action)
        self.reward += 0.1 * self.info["rings"]

    def random_step(self):
        return self.action_space.sample()

    def act(self, action):
        rounds_before = self.rounds
        # frameskip has to be incorporated on wrapper level
        for _ in range(self.frameskip):
            self._step(action)
        if self.rounds < rounds_before:
            self.terminal = True

    def act_play(self, action):
        rounds_before = self.rounds
        self._step(action)
        # self.env.render()
        if self.rounds < rounds_before:
            self.terminal = True

    @property
    def screen(self):
        a = resize(rgb2gray(self._screen), (self.screen_height, self.screen_width))
        return a

    @property
    def rounds(self):
        return self.info["rounds"]
